name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" and "dev" branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run docker tests
        run: ./run_tests.sh
      - name: Upload coverage files
        uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: ${{ env.COVERAGE_PATH }}

      - name: Upload README file
        uses: actions/upload-artifact@v2
        with:
          name: README
          path: ${{ env.README_PATH }}